# Generated by Django 4.1.4 on 2023-08-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
