# Generated by Django 4.1.4 on 2023-08-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=255)),
                ("texte", models.TextField(blank=True, null=True)),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
    ]
